---
include:
  - board: nice_nano_v2
    shield: sheriff_left
    # snippet: zmk-usb-logging
      # - studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: sheriff_right
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
