---
include:
  - board: nice_nano_v2
    shield: sheriff_left
    snippet: 
      - studio-rpc-usb-uart
      - zmk-usb-logging
  - board: nice_nano_v2
    shield: sheriff_right
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
